version: "2"
run:
  tests: false
linters:
  enable:
    - bodyclose
    - depguard
    - dupl
    - goconst
    - godot
    - godox
    - goprintffuncname
    - gosec
    - misspell
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - unparam
    - whitespace
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/gliderlabs/ssh
              desc: use github.com/charmbracelet/ssh instead
  exclusions:
    generated: lax
    presets:
      - common-false-positives
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
